config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      post :username
    end
    member do
      put :password
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index
  resources :characters do
    member do
      get :replace
      post :do_replace
    end
    collection { get :facecasts }
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end

  # Forums
  resources :boards do collection { post :mark } end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
    collection { get :search }
  end
  resources :tags

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: :show
      resources :board_sections do # TODO other types
        collection { post :reorder }
      end
      resources :characters, only: [:show, :update]
      resources :posts, only: :show
    end
  end

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount ResqueWeb::Engine => "/resque_web"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  has_many :character_tags, dependent: :destroy
  has_many :characters, through: :character_tags

  validates_presence_of :user, :name
  validates :name, uniqueness: { scope: :type }

  def editable_by?(user)
    user.try(:admin?)
  end

  def as_json(*args, **kwargs)
    {id: self.id, text: self.name}
  end

  def merge_with(other_tag)
    transaction do
      PostTag.where(tag_id: other_tag.id).where(post_id: post_tags.pluck('distinct post_id')).delete_all
      PostTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      other_tag.destroy
    end
  end
end

app/views/templates/_editor.haml
%tr
  %th.sub Name
  %td.even= f.text_field :name, placeholder: "Template Name", class: 'text'
%tr
  %th.sub.vtop Description
  %td.odd= f.text_area :description
%tr
  %th.sub.vtop Characters
  %td.even
    - unless @template.new_record?
      - @template.characters.order('LOWER(name)').each do |char|
        = check_box_tag "template[character_ids][]", char.id, true, id: "template_character_ids_#{char.id}"
        = label_tag "template_character_ids_#{char.id}", char.name
        %br
    - current_user.characters.where(template_id: nil).order('LOWER(name)').each do |char|
      = check_box_tag "template[character_ids][]", char.id, false, id: "template_character_ids_#{char.id}"
      = label_tag "template_character_ids_#{char.id}", char.name
      %br
    =# collection_check_boxes :template, :characters, @template.characters + current_user.characters.where(template_id: nil), :id, :name
%tr
  %th.subber{colspan: 2}= submit_tag "Save", class: 'button'

app/views/templates/_single.haml
%table
  %tr
    %th.subber.padding-10{colspan: 6}
      = title
      - if template.user_id == current_user.try(:id)
        = link_to new_character_path(template_id: template.id) do
          .link-box.green + New Instance
        = link_to edit_template_path(template) do
          .link-box.blue
            = image_tag '/images/pencil.png'
            Edit Template
        = link_to template_path(template), :method => :delete, confirm: 'Are you sure you want to delete this template?' do
          .link-box.red x Delete Template
      - if page_view == 'list'
        - @template = template
        = render partial: 'characters/list_view'
      - else
        - @characters = template.characters
        = render partial: 'characters/icon_view'

app/views/templates/edit.haml
- content_for :breadcrumbs do
  = link_to "Characters", characters_path
  &raquo;
  = link_to @template.name, template_path(@template)
  &raquo;
  %b Edit

= form_for @template, url: template_path(@template), method: :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Edit Template
    = render partial: 'editor', locals: {f: f}

app/views/templates/new.haml
- content_for :breadcrumbs do
  = link_to "Characters", characters_path
  &raquo;
  %b New Template

= form_for @template, :url => templates_path, :method => :post do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} New Template
    = render partial: 'editor', locals: {f: f}

app/views/templates/show.haml
- content_for :breadcrumbs do
  - if @template.user_id == current_user.try(:id)
    = link_to "Characters", characters_path
  - else
    = link_to "#{@template.user.username}", user_path(@template.user)
    &raquo;
    = link_to "#{@template.user.username}'s Characters", user_characters_path(@template.user)
  &raquo;
  %b= @template.name

%table
  %tr
    %th{colspan: 6}
      Template: #{@template.name}
      - if @template.user_id == current_user.try(:id)
        = link_to new_character_path(template_id: @template.id) do
          .link-box.green + New Instance
        = link_to edit_template_path(@template) do
          .link-box.blue
            = image_tag '/images/pencil.png'
            Edit Template
        = link_to template_path(@template), :method => :delete, confirm: 'Are you sure you want to delete this template?' do
          .link-box.red x Delete Template
      = link_to url_for(view: 'icons') do
        .view-button{class: (:selected unless page_view == 'list')}
          = image_tag '/images/grid.png', class:'icon-view', alt: ''
          Icons
      = link_to url_for(view: 'list') do
        .view-button{class: (:selected if page_view == 'list')}
          = image_tag '/images/list.png', class:'list-view', alt: ''
          List
  - if page_view == 'list'
    = render partial: 'characters/list_view'
  - else
    = render partial: 'characters/icon_view', locals: {characters: @template.characters.order('name asc').includes(:default_icon)}
- if @posts.present?
  %br
  - content_for :posts_title do 'Posts with Template Instances' end
  = render partial: 'posts/list', locals: {posts: @posts, path: :template_path}