config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      post :username
    end
    member do
      put :password
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index
  resources :characters do
    member do
      get :replace
      post :do_replace
    end
    collection { get :facecasts }
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end

  # Forums
  resources :boards do collection { post :mark } end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
    collection { get :search }
  end
  resources :tags

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: :show
      resources :board_sections do # TODO other types
        collection { post :reorder }
      end
      resources :characters, only: [:show, :update]
      resources :posts, only: :show
    end
  end

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount ResqueWeb::Engine => "/resque_web"
end

app/models/character.rb
class Character < ActiveRecord::Base
  include Presentable

  belongs_to :user
  belongs_to :template
  belongs_to :default_icon, class_name: Icon
  belongs_to :character_group
  has_many :replies
  has_many :posts

  has_many :characters_galleries
  has_many :galleries, through: :characters_galleries, after_remove: :reorder_galleries
  has_many :icons, through: :galleries, group: 'icons.id', order: 'LOWER(keyword)'

  has_many :character_tags, inverse_of: :character, dependent: :destroy
  has_many :tags, through: :character_tags, source: :all_tags, source_type: 'Tag' # TODO THIS IS BROKEN does not filter subtypes like setting

  has_many :settings, through: :character_tags, source: :all_tags, source_type: 'Setting'

  validates_presence_of :name, :user
  validate :valid_template, :valid_group, :valid_galleries, :valid_default_icon

  attr_accessor :new_template_name, :group_name

  nilify_blanks

  def icon
    @icon ||= default_icon || galleries.detect(&:default_icon).try(:default_icon)
  end

  def recent_posts
    return @recent unless @recent.nil?
    reply_ids = replies.group(:post_id).select(:post_id).map(&:post_id)
    post_ids = posts.select(:id).map(&:id)
    @recent ||= Post.where(id: (post_ids + reply_ids).uniq).order('tagged_at desc')
  end

  def selector_name
    [name, template_name, screenname].compact.join(' | ')
  end

  def reorder_galleries(gallery=nil)
    # public so that it can be called from CharactersGallery.after_destroy
    galleries = CharactersGallery.where(character_id: id).order('section_order asc')
    return unless galleries.present?

    galleries.each_with_index do |other, index|
      next if other.section_order == index
      other.section_order = index
      other.save
    end
  end

  private

  def valid_template
    unless template_id == 0
      errors.add(:template, "must be yours") if template.present? && template.user_id != user.id
      return
    end
    @template = Template.new(user: user, name: new_template_name)
    return if @template.valid?
    @template.errors.messages.each do |k, v|
      v.each { |val| errors.add('template '+k.to_s, val) }
    end
  end

  def valid_group
    return unless character_group_id == 0
    @group = CharacterGroup.new(user: user, name: group_name)
    return if @group.valid?
    @group.errors.messages.each do |k, v|
      v.each { |val| errors.add('group '+k.to_s, val) }
    end
  end
  
  def valid_galleries
    if galleries.present? && galleries.detect{|g| g.user_id != user.id}
      errors.add(:galleries, "must be yours")
    end
  end
  
  def valid_default_icon
    if default_icon.present? && default_icon.user_id != user_id
      errors.add(:default_icon, "must be yours")
    end
  end
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < Api::ApiController
  before_filter :login_required, only: :update
  before_filter :find_character
  before_filter :require_permission, only: :update

  resource_description do
    description 'Viewing and editing characters'
  end

  api :GET, '/characters/:id', 'Load a single character as a JSON resource'
  param :id, :number, required: true, desc: 'Character ID'
  error 404, "Character not found"
  example "'errors': [{'message': 'Character could not be found.'}]"
  example "'data': {
  'id': 1,
  'name': 'Character Example',
  'screenname': 'char-example',
  'default': {
    'id': 2,
    'url': 'http://www.example.com/image.png',
    'keyword': 'icon'
  },
  'galleries': [
    {
      'name': 'Example 1',
      'icons': []
    }, {
      'name': 'Example 2',
      'icons': [
        {
          'id': 2,
          'url': 'http://www.example.com/image.png',
          'keyword': 'icon'
        }, {
          'id': 3,
          'url': 'http://www.example.com/image2.png',
          'keyword': 'icon2'
      }]
  }]
}"
  def show
    render json: {data: @character.as_json(include: [:galleries, :default])}
  end

  api :PUT, '/characters/:id', 'Update a given character'
  param :id, :number, required: true, desc: 'Character ID'
  error 401, "You must be logged in"
  error 403, "Character is not editable by the user"
  error 404, "Character not found"
  error 422, "Invalid parameters provided"
  example "'errors': [{'message': 'You must be logged in to view that page.'}]"
  example "'errors': [{'message': 'You do not have permission to perform this action.'}]"
  example "'errors': [{'message': 'Character could not be found.'}]"
  example "'errors': [{'message': \"Name can't be blank\"}, {'message': 'Default icon could not be found'}]"
  example "'data': {
  'id': 1,
  'name': 'Character Example',
  'screenname': 'char-example',
  'default': {
    'id': 2,
    'url': 'http://www.example.com/image.png',
    'keyword': 'icon'
  }
}"
  def update
    render json: {data: @character.as_json(include: [:default])} and return unless params[:character]

    errors = []
    if params[:character][:default_icon_id].present?
      errors << {message: "Default icon could not be found"} unless Icon.find_by_id(params[:character][:default_icon_id])
    end

    @character.assign_attributes(params[:character])
    errors += @character.errors.full_messages.map { |msg| {message: msg} } unless @character.valid?
    render json: {errors: errors}, status: :unprocessable_entity and return unless errors.empty?

    @character.save
    render json: {data: @character.as_json(include: [:default])}
  end

  private

  def find_character
    unless @character = Character.find_by_id(params[:id])
      error = {message: "Character could not be found."}
      render json: {errors: [error]}, status: :not_found and return
    end
  end

  def require_permission
    access_denied unless @character.user == current_user
  end
end

app/controllers/characters_controller.rb
# frozen_string_literal: true
class CharactersController < ApplicationController
  before_filter :login_required, :except => [:index, :show, :facecasts]
  before_filter :find_character, :only => [:show, :edit, :update, :destroy, :icon, :replace, :do_replace]
  before_filter :find_group, :only => :index
  before_filter :require_own_character, :only => [:edit, :update, :destroy, :icon, :replace, :do_replace]
  before_filter :build_editor, :only => [:new, :create, :edit, :update]

  def index
    (return if login_required) unless params[:user_id].present?

    @user = User.find_by_id(params[:user_id]) || current_user
    unless @user
      flash[:error] = "User could not be found."
      redirect_to users_path and return
    end

    @page_title = if @user.id == current_user.try(:id)
      "Your Characters"
    else
      @user.username + "'s Characters"
    end
  end

  def new
    @page_title = 'New Character'
    @character = Character.new(template_id: params[:template_id])
  end

  def create
    reorder_galleries and return if params[:commit] == "reorder"

    @character = Character.new((params[:character] || {}).merge(user: current_user))

    if @character.valid?
      save_character_with_extras
      flash[:success] = "Character saved successfully."
      redirect_to character_path(@character)
    else
      @page_title = 'New Character'
      flash.now[:error] = "Your character could not be saved."
      render :action => :new
    end
  end

  def show
    @page_title = @character.name
    @posts = posts_from_relation(@character.recent_posts)
    use_javascript('characters/show') if @character.user_id == current_user.try(:id)
    use_javascript('galleries/index') if @character.galleries.ordered.present?
  end

  def edit
    @page_title = 'Edit Character: ' + @character.name
  end

  def update
    @character.assign_attributes(params[:character])

    if @character.valid?
      save_character_with_extras
      flash[:success] = "Character saved successfully."
      redirect_to character_path(@character)
    else
      flash.now[:error] = "Your character could not be saved."
      @page_title = 'Edit Character: ' + @character.name
      render :action => :edit
    end
  end

  def destroy
    @character.destroy
    flash[:success] = "Character deleted successfully."
    redirect_to characters_path
  end

  def facecasts
    @page_title = 'Facecasts'
    chars = Character.where('pb is not null').includes(:user, :template)
    @pbs = {}

    if params[:sort] == "name"
      chars.each do |character|
        key = character.template || character
        @pbs[key] ||= []
        @pbs[key] << character.pb
      end
    elsif params[:sort] == "writer"
      chars.each do |character|
        @pbs[character.user] ||= {}
        @pbs[character.user][character.pb] ||= []
        @pbs[character.user][character.pb] << (character.template || character)
      end
    else
      chars.each do |character|
        @pbs[character.pb] ||= []
        @pbs[character.pb] << (character.template || character)
      end
    end
  end

  def replace
    @page_title = 'Replace Character: ' + @character.name
    if @character.template
      @alts = @character.template.characters
    else
      @alts = @character.user.characters.where(template_id: nil)
    end
    @alts -= [@character]
    use_javascript('icons')

    icons = @alts.map do |alt|
      if alt.icon.present?
        [alt.id, {url: alt.icon.url, keyword: alt.icon.keyword}]
      else
        [alt.id, {url: '/images/no-icon.png', keyword: 'No Icon'}]
      end
    end
    gon.gallery = Hash[icons]
    gon.gallery[''] = {url: '/images/no-icon.png', keyword: 'No Character'}

    @alt_dropdown = @alts.map do |alt|
      name = alt.name
      name += ' | ' + alt.screenname if alt.screenname
      name += ' | ' + alt.template_name if alt.template_name
      name += ' | ' + alt.setting if alt.setting
      [name, alt.id]
    end

    all_posts = Post.where(character_id: @character.id) + Post.where(id: Reply.where(character_id: @character.id).pluck('distinct post_id'))
    @posts = all_posts.uniq
  end

  def do_replace
    unless params[:icon_dropdown].blank? || new_char = Character.find_by_id(params[:icon_dropdown])
      flash[:error] = "Character could not be found."
      redirect_to replace_character_path(@character)
    end

    if new_char && new_char.user_id != current_user.id
      flash[:error] = "That is not your character."
      redirect_to replace_character_path(@character)
    end

    Post.transaction do
      replies = Reply.where(character_id: @character.id)
      replies = replies.where(post_id: params[:post_ids]) if params[:post_ids].present?
      replies.update_all(character_id: new_char.try(:id))

      posts = Post.where(character_id: @character.id)
      posts = posts.where(id: params[:post_ids]) if params[:post_ids].present?
      posts.update_all(character_id: new_char.try(:id))
    end

    flash[:success] = "All uses of this character have been replaced."
    redirect_to character_path(@character)
  end

  private

  def find_character
    unless @character = Character.find_by_id(params[:id])
      flash[:error] = "Character could not be found."
      redirect_to characters_path and return
    end
  end

  def find_group
    return unless params[:group_id].present?
    @group = CharacterGroup.find_by_id(params[:group_id])
  end

  def require_own_character
    if @character.user_id != current_user.id
      flash[:error] = "You do not have permission to edit that character."
      redirect_to characters_path and return
    end
  end

  def build_editor
    faked = Struct.new(:name, :id)
    new_template = faked.new('— Create New Template —', 0)
    @templates = current_user.templates.order('name asc') + [new_template]
    new_group = faked.new('— Create New Group —', 0)
    @groups = current_user.character_groups.order('name asc') + [new_group]
    use_javascript('characters/editor')
    gon.character_id = @character.try(:id) || ''
  end

  def save_character_with_extras
    Character.transaction do
      if template = @character.instance_variable_get('@template')
        template.save
        @character.template = template
      end
      if group = @character.instance_variable_get('@group')
        group.save
        @character.character_group = group
      end
      @character.save
    end
  end

  def reorder_galleries
    CharactersGallery.transaction do
      params[:changes].each do |id, order|
        cg = CharactersGallery.find_by_id(id)
        next unless cg
        cg.section_order = order
        cg.save
      end
    end
    render json: {}
  end
end

app/views/characters/_editor.haml
%tr
  %th.sub Name
  %td{class: cycle('even', 'odd')}= f.text_field :name, placeholder: "Character Name", class: 'text'
%tr
  %th.sub Nickname
  %td{class: cycle('even', 'odd')}= f.text_field :template_name, placeholder: "Template Nickname", class: 'text'
%tr
  %th.sub Screenname
  %td{class: cycle('even', 'odd')}= f.text_field :screenname, placeholder: "Screen Name", class: 'text'
%tr
  %th.sub Setting
  %td{class: cycle('even', 'odd')}= f.text_field :setting, placeholder: "Setting", class: 'text'
  /%td{class: cycle('even', 'odd')}= f.collection_select(:setting_ids,
  /  Setting.all, :id, :name, {selected: @character.settings.pluck(:id)}, {multiple: true})
%tr
  - klass = cycle('even', 'odd')
  %th.sub Template
  %td{class: klass}= f.collection_select :template_id, @templates, :id, :name, {include_blank: '— Choose Template —'}, {class: 'text'}
%tr#create_template{class: ('hidden' unless params[:character].try(:[], :template_id) == "0")}
  %th.sub &#8627; Name
  %td{class: klass}= f.text_field :new_template_name, placeholder: "Template Name", class: 'text'
- if current_user.galleries.present?
  %tr
    %th.sub Galleries
    %td{class: cycle('even', 'odd')}
      = f.collection_select(:gallery_ids,
      current_user.galleries.order('name asc'),
      :id, :name, {selected: @character.galleries.pluck(:id)}, {multiple: true})
%tr
  %th.sub Facecast
  %td{class: cycle('even', 'odd')}= f.text_field :pb, placeholder: "Facecast", class: 'text'
%tr
  %th.centered.subber{colspan: 2}= submit_tag "Save", class: 'button'

#selected-gallery
  %b Images
  %br
  Pick Default Icon (Optional):
  %br
  .gallery
    - galleries = @character.galleries.present? ? @character.galleries.ordered : [Struct.new(:id, :name, :icons).new(0, 'Galleryless', current_user.galleryless_icons || [])]
    - if galleries.present?
      - galleries.each do |gallery|
        %div{id: "gallery#{gallery.id}", :'data-id' => gallery.id }
          %br
          %b.gallery-name= gallery.name
          %br
          .gallery-icons
            - gallery.icons.order('LOWER(keyword)').each do |icon|
              - klass = 'icon character-icon'
              - klass += ' selected-icon' if icon == @character.default_icon
              = icon_tag icon, class: klass, id: icon.id

app/views/characters/_icon_view.haml
- if @template && @template.description.present?
  %tr
    %td.beige.padding-5{colspan: 6}= @template.description
%tr
  %td.green.left-align
    .gallery
      - characters.each do |character|
        .gallery-icon
          = link_to character_path(character) do
            - if character.icon
              = icon_tag character.icon
              %br
            - else
              <div class='icon gallery-no-icon'>&nbsp;</div>
              %br
            %span.character-name= character.name
            - if character.screenname.present?
              %br
              %span.character-screenname= surround('(', ')') { sanitize(character.screenname).gsub('_', '_<wbr>') }
          - if character.user_id == current_user.try(:id)
            .delete-button{ id: character.id }
              = link_to 'X', character_path(character), :method => :delete, confirm: 'Are you sure you want to delete '+character.name+'?'
      - unless characters.present?
        .centered — No characters yet —

app/views/characters/_list_section.haml
- unless @template
  %tr
    %td.beige.padding-10{colspan: 6}
      - if name.is_a? ActiveRecord::Base::Template
        %b
          Template:
          = link_to name.name, template_path(name)
        - if current_user.try(:id) == name.user_id
          = link_to new_character_path(template_id: name.id) do
            .link-box.green{style: 'font-size: 14px'} + New Instance
          = link_to edit_template_path(name) do
            .link-box.blue{style: 'font-size: 14px'}
              = image_tag '/images/pencil.png', class: 'vmid'
              Edit
          = link_to template_path(name), method: :delete, confirm: 'Are you sure you want to delete this template?' do
            .link-box.red{style: 'font-size: 14px'} x Delete
      - else
        %b= name
- if @template && @template.description.present?
  %tr
    %td.beige.padding-5{colspan: 6}= @template.description
- if characters.empty?
  %tr
    %td.centered.padding-5{class: cycle('even', 'odd'), colspan: 6} — No characters yet —
- else
  %tr
    - klass = cycle('even', 'odd')
    %td.padding-5{class: klass}
      %b Name
    %td.padding-5{class: klass}
      %b Nickname
    %td.padding-5{class: klass}
      %b Screenname
    %td.padding-5{class: klass}
      %b Facecast
    %td.padding-5{class: klass}
      %b Setting
    %td.padding-5{class: klass}
  - characters.order('name asc').each do |character|
    - klass = cycle('even', 'odd')
    %tr
      %td.padding-5{class: klass}
        = link_to character.name, character_path(character)
      %td.padding-5{class: klass, style:'width:15%'}= character.template_name
      %td.padding-5{class: klass, style:'width:15%'}= character.screenname
      %td.padding-5{class: klass, style:'width:20%'}= character.pb
      %td.padding-5{class: klass, style:'width:15%'}= character.setting

      %td.width-70.right-align{class: klass}
        - if @user.id == current_user.try(:id)
          = link_to edit_character_path(character) do
            = image_tag "/images/pencil.png"
          = link_to character_path(character), :method => :delete, confirm: 'Are you sure you want to delete '+character.name+'?' do
            = image_tag "/images/cross.png"
          &nbsp;

app/views/characters/_list_view.haml
- if @group
  - @group.characters.map(&:template).uniq.compact.sort_by(&:name).each do |template|
    = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
  - if @group.characters.where(template_id: nil).exists?
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @group.characters.where(template_id: nil).order('name asc')}
- elsif @template
  = render partial: 'characters/list_section', locals: {name: @template, characters: @template.characters}
- elsif @user.character_groups.exists?
  - @user.character_groups.order('id asc').each do |group|
    %tr
      %th.subber{colspan: 6}
        Group:
        = group.name
    - group.characters.map(&:template).uniq.compact.sort_by(&:name).each do |template|
      = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
    - if group.characters.where(template_id: nil).exists?
      = render partial: 'characters/list_section', locals: {name: "No Template", characters: group.characters.where(template_id: nil).order('name asc')}
  - if @user.characters.where(character_group_id: nil).exists?
    %tr
      %th{colspan: 6} Ungrouped Characters
    - @user.characters.where(character_group_id: nil).includes(:template).map(&:template).uniq.compact.sort_by(&:name).each do |template|
      - next if template.characters.where('character_group_id is not null').exists?
      = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @user.characters.where(character_group_id: nil).where(template_id: nil).order('name asc')}

- elsif @user.characters.exists?
  - @user.templates.order('name asc').each do |template|  
    = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}

  - unless @user.characters.where(template_id: nil).count.zero?
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @user.characters.where(template_id: nil).order('name asc')}
- else
  %tr
    %td.centered.padding-10{class: cycle('even', 'odd'), colspan: 6} — No characters yet —

app/views/characters/edit.haml
- content_for :breadcrumbs do
  = link_to "Characters", characters_path
  &raquo;
  - if @character.template
    = link_to @character.template.name, template_path(@character.template)
    &raquo;
  = link_to @character.name, character_path(@character)
  &raquo;
  %b Edit

= form_for @character, url: character_path(@character), method: :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2}= @character.name
    = render partial: 'editor', locals: {f: f}
    

app/views/characters/facecasts.haml
%table
  %tr
    %th{colspan: 4} Facecasts
  %tr
    %th.sub= link_to 'Facecast', url_for(sort: nil)
    %th.sub Type
    %th.sub= link_to 'Name', url_for(sort: 'name')
    %th.sub= link_to 'Writer', url_for(sort: 'writer')
  - if params[:sort] == "name"
    - characters = @pbs.keys.sort_by{ |char| char.name.downcase }
    - characters.each do |character|
      - pbs = @pbs[character].uniq
      - pbs.each do |pb|
        %tr
          - klass = cycle('even','odd')
          %td.padding-5{class: klass}= pb
          %td.padding-5{class: klass}= character.class
          %td.padding-5{class: klass}
            - if character.is_a? Character
              = link_to character.name, character_path(character)
            - else
              = link_to character.name, template_path(character)
          %td.padding-5{class: klass}= link_to character.user.username, user_path(character.user)
  - elsif params[:sort] == "writer"
    - authors = @pbs.keys.sort_by{ |a| a.username.downcase }
    - authors.each do |author|
      - pbs = @pbs[author].sort
      - pbs.each do |pb, characters|
        - uniq_chars = characters.uniq
        - uniq_chars.each do |character|
          %tr
            - klass = cycle('even','odd')
            %td.padding-5{class: klass}= pb
            %td.padding-5{class: klass}= character.class
            %td.padding-5{class: klass}
              - if character.is_a? Character
                = link_to character.name, character_path(character)
              - else
                = link_to character.name, template_path(character)
            %td.padding-5{class: klass}= link_to character.user.username, user_path(character.user)
  - else
    - @pbs.keys.sort_by(&:downcase).each do |pb|
      - characters = @pbs[pb].uniq
      - characters.each do |character|
        %tr
          - klass = cycle('even','odd')
          %td.padding-5{class: klass}= pb
          %td.padding-5{class: klass}= character.class
          %td.padding-5{class: klass}
            - if character.is_a? Character
              = link_to character.name, character_path(character)
            - else
              = link_to character.name, template_path(character)
          %td.padding-5{class: klass}= link_to character.user.username, user_path(character.user)

app/views/characters/index.haml
- content_for :breadcrumbs do
  - if @user.id != current_user.try(:id)
    = link_to "#{@user.username}", user_path(@user)
    &raquo;
    %b #{@user.username}'s Characters

%table
  %tr
    %th{colspan: 6}
      - if @group
        Character Group:
        = @group.name
      - else
        - if @user.id == current_user.try(:id)
          Your Characters
          = link_to new_character_path(character_group_id: @group.try(:id)) do
            .link-box.green + New Character
          = link_to new_template_path do
            .link-box.green + New Template
        - else
          = @user.username + "'s Characters"
      = link_to url_for(view: 'icons') do
        .view-button{class: (:selected unless page_view == 'list')}
          = image_tag '/images/grid.png', class: 'icon-view', alt: ''
          Icons
      = link_to url_for(view: 'list') do
        .view-button{class: (:selected if page_view == 'list')}
          = image_tag '/images/list.png', class: 'list-view', alt: ''
          List
  - if page_view == 'list'
    = render partial: 'list_view'
  - else
    = render partial: 'icon_view', locals: {characters: @user.characters.order('name asc').includes(:default_icon)}

app/views/characters/new.haml
= form_for @character, url: characters_path, method: :post do |f|
  = f.hidden_field :default_icon_id
  %table.form-table
    %tr
      %th.centered{colspan: 2} New Character
    = render partial: 'editor', locals: {f: f}

app/views/characters/replace.haml
- content_for :breadcrumbs do
  = link_to "Characters", characters_path
  - if @character.template
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
  &raquo;
  = link_to @character.name, character_path(@character)
  &raquo;
  %b Replace

= form_for @character, url: do_replace_character_path(@character), method: :post do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Replace All Uses of Character
    %tr
      %td.odd.centered{colspan: 2}
        .details *This does NOT replace icons*
    %tr
      %th.sub Current
      %th.sub New
    %tr
      %td.green.width-150.centered.vtop
        = icon_tag @character.icon
        %br
        = @character.name
      %td.green.width-150.centered
        - if @alts.first.try(:icon)
          = icon_tag @alts.first.icon, id: 'new_icon'
        - else
          = no_icon_tag id: 'new_icon'
        %br
        = select_tag :icon_dropdown, options_for_select(@alt_dropdown, @alts.first.try(:id)), prompt: "No Character"
    - if @posts.present?
      %tr
        %th.sub{colspan: 2} Optional: Select Post(s)
      %tr
        %td.odd.centered{colspan: 2}
          .details *If none are selected, replaces all uses*
    - @posts.each do |post|
      %tr
        %td{colspan: 2, class: cycle('even', 'odd')}
          = check_box_tag :'post_ids[]', post.id
          = link_to post.subject, post_path(post)
    %tr
      %th.subber{colspan: 2}= submit_tag "Replace", class: 'button'

app/views/characters/show.haml
- content_for :breadcrumbs do
  - if @character.user_id == current_user.try(:id)
    = link_to "Characters", characters_path
  - else
    = link_to "#{@character.user.username}", user_path(@character.user)
    &raquo;
    = link_to "#{@character.user.username}'s Characters", user_characters_path(@character.user)
  - if @character.template
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
  &raquo;
  %b= @character.name

.character-info
  - if @character.icon
    .character-icon
      = link_to icon_path(@character.icon) do
        = icon_tag @character.icon
  - if @character.screenname
    %b.character-screenname= @character.screenname
    %br
  %span.character-name= @character.name
  - if @character.template
    = surround '(', ')' do
      = link_to @character.template.name, template_path(@character.template), class: 'character-template'
  - if @character.template_name
    %br
    = precede 'Nickname: ' do
      %span.character-template-nickname=@character.template_name
  - if @character.pb
    %br
    = precede 'Facecast: ' do
      %span.character-pb= @character.pb
  - if @character.setting
    %br
    = precede 'Setting: ' do
      %span.character-setting= @character.setting
  - if logged_in? && current_user.id == @character.user_id
    %br
    = link_to 'Edit character', edit_character_path(@character), class: 'character-edit'
    %br
    = link_to 'Replace character', replace_character_path(@character), class: 'character-replace'
%br
- if @posts.present?
  - content_for :posts_title do 'Recent Threads' end
  = render partial: 'posts/list', locals: {posts: @posts, path: :character_path}
%br
- if @character.galleries.ordered.present?
  %table
    %thead
      %tr
        %th Galleries
    %tbody
      - @character.galleries.ordered.each do |gallery|
        = render partial: 'galleries/single', locals: {gallery: gallery, klass: 'subber', skip_forms: true, section: gallery.character_gallery_for(@character)}