config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      post :username
    end
    member do
      put :password
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index
  resources :characters do
    member do
      get :replace
      post :do_replace
    end
    collection { get :facecasts }
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end

  # Forums
  resources :boards do collection { post :mark } end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
    collection { get :search }
  end
  resources :tags

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: :show
      resources :board_sections do # TODO other types
        collection { post :reorder }
      end
      resources :characters, only: [:show, :update]
      resources :posts, only: :show
    end
  end

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount ResqueWeb::Engine => "/resque_web"
end

app/models/character.rb
class Character < ActiveRecord::Base
  include Presentable

  belongs_to :user
  belongs_to :template
  belongs_to :default_icon, class_name: Icon
  belongs_to :character_group
  has_many :replies
  has_many :posts

  has_many :characters_galleries
  has_many :galleries, through: :characters_galleries, after_remove: :reorder_galleries
  has_many :icons, through: :galleries, group: 'icons.id', order: 'LOWER(keyword)'

  has_many :character_tags, inverse_of: :character, dependent: :destroy
  has_many :tags, through: :character_tags, source: :all_tags, source_type: 'Tag' # TODO THIS IS BROKEN does not filter subtypes like setting

  has_many :settings, through: :character_tags, source: :all_tags, source_type: 'Setting'

  validates_presence_of :name, :user
  validate :valid_template, :valid_group, :valid_galleries, :valid_default_icon

  attr_accessor :new_template_name, :group_name

  nilify_blanks

  def icon
    @icon ||= default_icon || galleries.detect(&:default_icon).try(:default_icon)
  end

  def recent_posts
    return @recent unless @recent.nil?
    reply_ids = replies.group(:post_id).select(:post_id).map(&:post_id)
    post_ids = posts.select(:id).map(&:id)
    @recent ||= Post.where(id: (post_ids + reply_ids).uniq).order('tagged_at desc')
  end

  def selector_name
    [name, template_name, screenname].compact.join(' | ')
  end

  def reorder_galleries(gallery=nil)
    # public so that it can be called from CharactersGallery.after_destroy
    galleries = CharactersGallery.where(character_id: id).order('section_order asc')
    return unless galleries.present?

    galleries.each_with_index do |other, index|
      next if other.section_order == index
      other.section_order = index
      other.save
    end
  end

  private

  def valid_template
    unless template_id == 0
      errors.add(:template, "must be yours") if template.present? && template.user_id != user.id
      return
    end
    @template = Template.new(user: user, name: new_template_name)
    return if @template.valid?
    @template.errors.messages.each do |k, v|
      v.each { |val| errors.add('template '+k.to_s, val) }
    end
  end

  def valid_group
    return unless character_group_id == 0
    @group = CharacterGroup.new(user: user, name: group_name)
    return if @group.valid?
    @group.errors.messages.each do |k, v|
      v.each { |val| errors.add('group '+k.to_s, val) }
    end
  end
  
  def valid_galleries
    if galleries.present? && galleries.detect{|g| g.user_id != user.id}
      errors.add(:galleries, "must be yours")
    end
  end
  
  def valid_default_icon
    if default_icon.present? && default_icon.user_id != user_id
      errors.add(:default_icon, "must be yours")
    end
  end
end

app/models/post_view.rb
class PostView < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :user, :post

  def timestamp_attributes_for_create
    super + [:read_at]
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::ApiController
  resource_description do
    description 'Viewing and editing posts'
  end

  api :GET, '/posts/:id', 'Load a single post as a JSON resource'
  param :id, :number, required: true, desc: "Post ID"
  param :page, :number, required: false, desc: 'Page in results'
  error 403, "Post is not visible to the user"
  error 404, "Post not found"
  example "'errors': [{'message': 'Post could not be found.'}]"
  example "'errors': [{'message': 'You do not have permission to perform this action.'}]"
  example "'data': {
  'id': 1,
  'user': {
    'id': 1,
    'username': 'Marri1'
  },
  'board': {
    'id': 5,
    'name': 'Continuity'
  },
  'section': {
    'id': 6,
    'name': 'Subcontinuity',
    'order': 0
  },
  'subject': 'search',
  'description': 'example json',
  'content': 'Lorem ipsum...',
  'status': 0,
  'character': {
    'id': 3,
    'name': 'Character Example',
    'screenname': 'char-example'
  },
  'icon': null,
  'replies': [{
    'id': 1,
    'content': 'dolor sit amet',
    'character': null,
    'icon': null,
    'user': {
      'id': 2,
      'username': 'Marri2'
    }
  }, {
    'id': 2,
    'content': 'consectetur adipiscing elit',
    'character': null,
    'icon': {
      'id': 7,
      'url': 'http://www.example.com/image.png',
      'keyword': 'icon'
    },
    'user': {
      'id': 1,
      'username': 'Marri1'
    }
  }],
}"
  def show
    unless post = Post.find_by_id(params[:id])
      error = {message: "Post could not be found."}
      render json: {errors: [error]}, status: :not_found and return
    end

    access_denied and return unless post.visible_to?(current_user)

    replies = paginate(post.replies.order('id asc'), per_page: per_page)
    render json: {data: post.as_json(replies: replies)}
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true
require 'will_paginate/array'

class PostsController < WritableController
  before_filter :login_required, except: [:index, :show, :history, :warnings, :search, :stats]
  before_filter :find_post, only: [:show, :history, :stats, :warnings, :edit, :update, :destroy]
  before_filter :require_permission, only: [:edit, :destroy]
  before_filter :editor_setup, only: [:new, :edit]

  def index
    @posts = posts_from_relation(Post.order('tagged_at desc'))
    @page_title = 'Recent Threads'
  end

  def owed
    posts_started = Post.where(user_id: current_user.id).pluck('distinct id')
    posts_in = Reply.where(user_id: current_user.id).pluck('distinct post_id')
    ids = (posts_in + posts_started).uniq
    @posts = Post.where(id: ids).where('status != ?', Post::STATUS_COMPLETE).where('status != ?', Post::STATUS_ABANDONED).where('last_user_id != ?', current_user.id)
    @posts = @posts.where('status != ?', Post::STATUS_HIATUS).where('tagged_at > ?', 1.month.ago) if current_user.hide_hiatused_tags_owed?
    @posts = posts_from_relation(@posts.order('tagged_at desc'))
    @show_unread = true
    @hide_quicklinks = true
    @page_title = 'Tags Owed'
  end

  def unread
    @started = (params[:started] == 'true') || (params[:started].nil? && current_user.unread_opened)
    @posts = Post.joins("LEFT JOIN post_views ON post_views.post_id = posts.id AND post_views.user_id = #{current_user.id}")
    @posts = @posts.joins("LEFT JOIN board_views on board_views.board_id = posts.board_id AND board_views.user_id = #{current_user.id}")
    @posts = @posts.where("post_views.user_id IS NULL OR (date_trunc('second', post_views.read_at) < date_trunc('second', posts.tagged_at) AND post_views.ignored = '0')")
    @posts = @posts.where("board_views.user_id IS NULL OR (date_trunc('second', board_views.read_at) < date_trunc('second', posts.tagged_at) AND board_views.ignored = '0')")
    @posts = posts_from_relation(@posts.order('tagged_at desc'), true, false)
    @posts = @posts.select { |p| p.visible_to?(current_user) }
    @posts = @posts.select { |p|  @opened_ids.include?(p.id) } if @started
    @posts = @posts.paginate(per_page: 25, page: page)
    @hide_quicklinks = true
    @page_title = @started ? 'Opened Threads' : 'Unread Threads'
  end

  def mark
    posts = Post.where(id: params[:marked_ids])
    posts.select! do |post|
      post.visible_to?(current_user)
    end
    if params[:commit] == "Mark Read"
      posts.each { |post| post.mark_read(current_user) }
      flash[:success] = posts.size.to_s + " posts marked as read."
    else
      posts.each { |post| post.ignore(current_user) }
      flash[:success] = posts.size.to_s + " posts hidden from this page."
    end
    redirect_to unread_posts_path
  end

  def hidden
    @hidden_boardviews = BoardView.where(user_id: current_user.id).where(ignored: true).includes(:board)
    hidden_post_ids = PostView.where(user_id: current_user.id).where(ignored: true).pluck('distinct post_id')
    @hidden_posts = posts_from_relation(Post.where(id: hidden_post_ids))
    @page_title = 'Hidden Posts & Boards'
  end

  def unhide
    if params[:unhide_boards].present?
      board_ids = params[:unhide_boards].map(&:to_i).compact.uniq
      views_to_update = BoardView.where(user_id: current_user.id).where(board_id: board_ids)
      views_to_update.each do |view| view.update_attributes(ignored: false) end
    end

    if params[:unhide_posts].present?
      post_ids = params[:unhide_posts].map(&:to_i).compact.uniq
      views_to_update = PostView.where(user_id: current_user.id).where(post_id: post_ids)
      views_to_update.each do |view| view.update_attributes(ignored: false) end
    end

    redirect_to hidden_posts_path
  end

  def new
    @post = Post.new(character: current_user.active_character, user: current_user)
    @post.board_id = params[:board_id]
    @post.icon_id = (current_user.active_character ? current_user.active_character.icon.try(:id) : current_user.avatar_id)
    @page_title = 'New Post'
  end

  def create
    preview(:post, posts_path) and return if params[:button_preview].present?

    @post = Post.new(params[:post])
    @post.user = @post.last_user = current_user

    create_new_tags if @post.valid?

    if @post.save
      flash[:success] = "You have successfully posted."
      redirect_to post_path(@post)
    else
      flash.now[:error] = {}
      flash.now[:error][:array] = @post.errors.full_messages
      flash.now[:error][:message] = "Your post could not be saved because of the following problems:"
      editor_setup
      @page_title = 'New Post'
      render :action => :new
    end
  end

  def show
    render action: :flat, layout: false and return if params[:view] == 'flat'
    show_post
  end

  def history
  end

  def stats
  end

  def preview(method, path)
    @written = Post.new(params[:post])
    @post = @written
    @written.user = current_user
    @url = path
    @method = method

    editor_setup

    @page_title = 'Previewing: ' + @post.subject.to_s
    render action: :preview
  end

  def edit
  end

  def update
    mark_unread and return if params[:unread].present?
    mark_hidden and return if params[:hidden].present?

    require_permission
    return if performed?

    change_status and return if params[:status].present?
    change_authors_locked and return if params[:authors_locked].present?
    preview(:put, post_path(params[:id])) and return if params[:button_preview].present?

    @post.assign_attributes(params[:post])
    @post.board ||= Board.find(3)

    create_new_tags if @post.valid?

    if @post.save
      flash[:success] = "Your post has been updated."
      redirect_to post_path(@post)
    else
      flash.now[:error] = {}
      flash.now[:error][:array] = @post.errors.full_messages
      flash.now[:error][:message] = "Your post could not be saved because of the following problems:"
      editor_setup
      render :action => :edit
    end
  end

  def mark_unread
    if params[:at_id].present?
      reply = Reply.find(params[:at_id])
      if reply && reply.post == @post
        board_read = @post.board.last_read(current_user)
        if board_read && board_read > reply.created_at
          flash[:error] = "You have marked this continuity read more recently than that reply was written; it will not appear in your Unread posts."
          Message.create(recipient_id: 1, sender_id: 1, subject: 'Unread at failure', message: "#{current_user.username} tried to mark post #{@post.id} unread at reply #{reply.id}")
        else
          @post.mark_read(current_user, reply.created_at - 1.second, true)
          flash[:success] = "Post has been marked as read until reply ##{reply.id}."
        end
      end
      return redirect_to unread_posts_path
    end

    @post.views.where(user_id: current_user.id).destroy_all
    flash[:success] = "Post has been marked as unread"
    redirect_to unread_posts_path
  end

  def mark_hidden
    if params[:hidden].to_s == 'true'
      @post.ignore(current_user)
      flash[:success] = "Post has been hidden"
    else
      @post.unignore(current_user)
      flash[:success] = "Post has been unhidden"
    end
    redirect_to post_path(@post)
  end

  def change_status
    begin
      new_status = Post.const_get('STATUS_'+params[:status].upcase)
    rescue NameError
      flash[:error] = "Invalid status selected."
    else
      @post.status = new_status
      @post.save
      flash[:success] = "Post has been marked #{params[:status]}."
    end
    redirect_to post_path(@post)
  end

  def change_authors_locked
    @post.authors_locked = (params[:authors_locked] == 'true')
    @post.save
    flash[:success] = "Post has been #{@post.authors_locked? ? 'locked to' : 'unlocked from'} current authors."
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to boards_path
  end

  def search
    @page_title = 'Browse Posts'
    return unless params[:commit].present?

    @search_results = Post.order('tagged_at desc').includes(:board)
    @search_results = @search_results.where(board_id: params[:board_id]) if params[:board_id].present?
    @search_results = @search_results.where(id: Setting.find(params[:setting_id]).post_tags.pluck(:post_id)) if params[:setting_id].present?
    @search_results = @search_results.search(params[:subject]).where('subject LIKE ?', "%#{params[:subject]}%") if params[:subject].present?
    @search_results = @search_results.where(status: Post::STATUS_COMPLETE) if params[:completed].present?
    if params[:author_id].present?
      post_ids = Reply.where(user_id: params[:author_id]).pluck('distinct post_id')
      where = Post.where(user_id: params[:author_id]).where(id: post_ids).where_values.reduce(:or)
      @search_results = @search_results.where(where)
    end
    if params[:character_id].present?
      post_ids = Reply.where(character_id: params[:character_id]).pluck('distinct post_id')
      where = Post.where(character_id: params[:character_id]).where(id: post_ids).where_values.reduce(:or)
      @search_results = @search_results.where(where)
    end
    @search_results = @search_results.paginate(page: page, per_page: 25)
  end

  def warnings
    if logged_in?
      @post.hide_warnings_for(current_user)
      flash[:success] = "Content warnings have been hidden for this thread. Proceed at your own risk. Please be aware that this will reset if new warnings are added later."
    else
      session[:ignore_warnings] = true
      flash[:success] = "All content warnings have been hidden. Proceed at your own risk."
    end
    params = {}
    params[:page] = page unless page.to_s == '1'
    params[:per_page] = per_page unless per_page.to_s == (current_user.try(:per_page) || 25).to_s
    redirect_to post_path(@post, params)
  end

  private

  def find_post
    @post = Post.find_by_id(params[:id])

    unless @post
      flash[:error] = "Post could not be found."

app/views/posts/_list_item.haml
%tr
  - klass = cycle('even', 'odd')
  - replies_count = post.replies.count
  %td.post-completed{class: [klass, (post.completed? ? 'post-complete' : 'post-incomplete')]}
    - if post.completed?
      = image_tag "/images/book.png", class: 'vmid', title: "Thread Complete"
    - if post.on_hiatus?
      = image_tag "/images/hourglass.png", class: 'vmid', title: "Thread On Hiatus"
    - if post.abandoned?
      = image_tag "/images/book_grey.png", class: 'vmid', title: "Thread Abandoned"
    - if !current_user.try(:hide_warnings) && post.content_warnings.exists?
      = image_tag "/images/exclamation.png", class: 'vmid', title: "Content Warning: " + post.content_warnings.pluck(:name).join(', '), alt: '!'
  %td.post-subject{class: klass}
    - if logged_in? && (@show_unread || (!@unread_ids.nil? && @unread_ids.include?(post.id)))
      = link_to post_path(post, page: 'unread', anchor: 'unread') do
        = image_tag unread_img, class: 'vmid', title: 'First Unread'
    - if logged_in? && @opened_ids.present? && !@opened_ids.include?(post.id)
      %b= link_to post.subject, post_path(post), title: strip_tags(post.description)
    - else
      = link_to post.subject, post_path(post), title: strip_tags(post.description)
    - if !@hide_quicklinks && (!logged_in? || per_page > 0)
      - total_pages = (replies_count.to_f / per_page).ceil
      - if total_pages > 1
        = surround '[', ']' do
          - if total_pages <= 6
            - params = {}
            - total_pages.times do |index|
              - params[:page] = index + 1 unless index == 0
              = link_to (index + 1), post_path(post, params)
          - else
            = link_to 1, post_path(post)
            = link_to 2, post_path(post, page: 2)
            = link_to 3, post_path(post, page: 3)
            \...
            - (total_pages-2).upto(total_pages) do |index|
              = link_to (index), post_path(post, page: index)
  - unless local_assigns[:hide_continuity]
    %td.post-board{class: klass}= link_to post.board_name, board_path(post.board_id)
  %td.post-authors{class: klass}= post.authors.sort_by { |author| author.username.downcase }.map { |author| link_to author.username, user_path(author) }.join(', ').html_safe
  %td.width-70.post-replies{class: klass}= replies_count
  - if logged_in? && local_assigns[:show_unread_count]
    %td.width-70{class: klass}
      - if @opened_ids.include?(post.id) && @unread_ids.include?(post.id)
        = Reply.where(post_id: post.id).where('created_at > ?', post.last_read(current_user)).count
      - else
        \-
  %td.post-time{class: klass}
    = pretty_time(post.tagged_at)
    by
    = link_to post.last_user_name, user_path(post.last_user_id)
  - if local_assigns[:check_box_name]
    %td.padding-right-10{class: klass}= check_box_tag check_box_name, post.id, false, class: 'checkbox'

app/views/posts/_write_post.haml
- content_for :form do
  = form_for post, :url => url, :method => method, :html => { :id => 'post_form' } do |f|
    = f.label :board_id, 'Continuity:'
    = f.select :board_id, options_from_collection_for_select(Board.order('pinned DESC, LOWER(name)').select {|b| current_user.writes_in?(b) }, :id, :name, post.board_id)
    %br
    #section{class: ('hidden' unless post.board && post.board.board_sections.exists?)}
      = f.label :section_id, 'Continuity section:'
      = f.select :section_id, options_from_collection_for_select(BoardSection.where(board_id: post.board_id).order('section_order asc'), :id, :name, post.section_id), include_blank: '— Choose Section —'
    = f.label :privacy, 'Privacy:'
    = f.select :privacy, options_from_collection_for_select(post_privacy_settings.to_a, :second, :first, post.privacy)
    #access_list
      = f.label :viewer_ids, '&#8627; Who can view this post? '.html_safe
      = f.collection_select(:viewer_ids, User.where('id != ?', post.user_id).order('username asc'),
      :id, :username, {selected: post.viewer_ids}, {multiple: true})
    %br
    = f.label :setting_ids, 'Setting:'
    = f.select :setting_ids, options_from_collection_for_select(@settings, :id, :name, post.setting_ids || post.settings.map(&:id)), {}, {multiple: true}
    %br
    = f.label :warning_ids, 'Content Warnings:'
    = f.select :warning_ids, options_from_collection_for_select(@warnings, :id, :name, post.warning_ids || post.content_warnings.map(&:id)), {}, {multiple: true}
    %br
    = f.label :tag_ids, 'Tags:'
    = f.select :tag_ids, options_from_collection_for_select(@tags, :id, :name, post.tag_ids || post.post_tags.map(&:tag_id)), {}, {multiple: true}
    %hr
    - unless post.id.present? && !post.editable_by?(current_user)
      .view-button#rtf{class: ('selected' if current_user.default_editor == 'rtf')} Rich Text
      .view-button#html{class: ('selected' if current_user.default_editor == 'html')} HTML
    = f.label :subject, 'Subject:'
    = f.text_field :subject, placeholder: 'Subject'
    %br
    = f.label :description, 'Description:'
    = f.text_field :description, placeholder: 'Description'
    .details (Optional: describe the thread's setting and major players, e.g. A Bell and Vorkosigans in Chronicle)
    - if post.id.present? && !post.editable_by?(current_user)
      = submit_tag 'Save', class: 'button', id: 'submit_button', disable_with: 'Saving...'
    - else
      %br
      #post-form-wrapper
        = f.text_area :content, class: 'tinymce'
        = f.hidden_field :character_id, id: 'reply_character_id'
        = f.hidden_field :icon_id, id: 'reply_icon_id'
        = submit_tag (method == :put ? 'Save' : "Post"), class: 'button', id: 'submit_button', disable_with: 'Saving...'
        = submit_tag "Preview", class: 'button', id: 'preview_button', name: 'button_preview'

- if post.id.present? && !post.editable_by?(current_user)
  #post-editor.padding-10= yield :form
- else
  = render partial: 'editor', locals: {item: post}

app/views/posts/edit.haml
- content_for :breadcrumbs do
  = link_to "Continuities", boards_path
  &raquo;
  = link_to @post.board.name, board_path(@post.board)
  - if @post.section
    &raquo;
    = link_to @post.section.name, board_section_path(@post.section)
  &raquo;
  = link_to @post.subject, post_path(@post)
  &raquo;
  %b Edit

.post-header
  .padding-15 Edit post
= render partial: 'write_post', locals: { post: @post, url: post_path(@post), method: :put }

app/views/posts/hidden.haml
= form_tag unhide_posts_path, method: :post do
  %table
    %tr
      %th{colspan: 7}
        Hidden from Unread
        = link_to unread_posts_path  do
          .view-button Unread &raquo;
    %tr
      %th.subber{colspan: 7} Continuities
    - @hidden_boardviews.each do |view|
      %tr
        - klass = cycle('even, odd')
        %td.padding-10{class: klass}
        %td.padding-10{class: klass, colspan: 5}
          = link_to view.board.name, board_path(view.board)
        %td{class: klass}= check_box_tag :"unhide_boards[]", view.board_id, params[:unhide_boards].try(:include?, view.board_id.to_s), class: 'no-margin'
    - if @hidden_boardviews.empty?
      %td.padding-10.centered{class: cycle('even', 'odd'), colspan: 7} — No continuities hidden —
    %tr
      %th.subber{colspan: 7} Posts
    - @hidden_posts.each do |post|
      = render partial: 'posts/list_item', locals: {post: post, check_box_name: 'unhide_posts[]'}
    - if @hidden_posts.empty?
      %td.padding-10.centered{class: cycle('even', 'odd'), colspan: 7} — No posts hidden —
    - if @hidden_posts.present? || @hidden_boardviews.present?
      %tr
        %td.right-align.padding-5{class: cycle('even', 'odd'), colspan: 7}
          = submit_tag "Show in Unread", class: 'button'

app/views/posts/index.haml
- content_for :posts_title do
  Most Recently Updated Threads
= render partial: 'list', locals: {posts: @posts}

app/views/posts/new.haml
.post-header
  .padding-15 Create a new post
= render partial: 'write_post', locals: { post: @post, url: posts_path, method: :post }

app/views/posts/stats.haml
- content_for :breadcrumbs do
  = link_to "Continuities", boards_path
  &raquo;
  = link_to @post.board.name, board_path(@post.board)
  - if @post.section
    &raquo;
    = link_to @post.section.name, board_section_path(@post.section)
  &raquo;
  = link_to @post.subject, post_path(@post)
  &raquo;
  %b Stats

%table#stats
  %thead
    %tr
      %th{colspan: 2}
        Stats:
        = link_to @post.subject, post_path(@post)
  %tbody
    %tr
      %td.sub.width-150 Authors
      %td.even= @post.authors.sort_by { |author| author.username.downcase }.map { |author| link_to author.username, user_path(author) }.join(', ').html_safe
    - if @post.settings.present?
      %tr
        %td.sub.width-150 Setting
        %td{class: cycle('odd', 'even')}= @post.settings.map { |tag| link_to tag.name, tag_path(tag) }.join(', ').html_safe
    %tr
      %td.sub.width-150.vtop Characters
      %td{class: cycle('odd', 'even')}
        - if @post.characters.count > 2
          %ul
            - @post.characters.each do |character|
              %li= link_to character.name, character_path(character)
        - else
          = @post.characters.map { |character| link_to character.name, character_path(character) }.join(', ').html_safe
    - if @post.content_warnings.present?
      %tr
        %td.sub.width-150 Content Warnings
        %td{class: cycle('odd', 'even')}= @post.content_warnings.map { |tag| link_to tag.name, tag_path(tag) }.join(', ').html_safe
    - if (tags = @post.tags.where(type: nil)).present?
      %tr
        %td.sub.width-150 Tags
        %td{class: cycle('odd', 'even')}= tags.map { |tag| link_to tag.name, tag_path(tag) }.join(', ').html_safe
    %tr
      %td.sub.width-150 Word Count
      %td{class: cycle('odd', 'even')}= @post.total_word_count
    %tr
      %td.sub.width-150 Audience
      %td{class: cycle('odd', 'even')}
        - case @post.privacy
        - when Post::PRIVACY_PUBLIC
          = image_tag "/images/world.png", class: 'vmid', title: "Public"
          Public
        - when Post::PRIVACY_REGISTERED
          = image_tag "/images/star.png", class: 'vmid', title: "Constellation Users"
          Constellation Users
        - when Post::PRIVACY_LIST
          = image_tag "/images/group.png", class: 'vmid', title: "Access list"
          Access List -
          - @post.post_viewers.each_with_index do |viewer, i|
            - if i < @post.post_viewers.count - 1
              = succeed ',' do
                = link_to viewer.user.username, user_path(viewer.user)
            - else
              = link_to viewer.user.username, user_path(viewer.user)
        - else
          = image_tag "/images/lock.png", class: 'vmid', title: "Private"
          Private
    %tr
      %td.sub.width-150 Time Begun
      %td{class: cycle('odd', 'even')}= pretty_time(@post.created_at)
    %tr
      %td.sub.width-150 Time Last Updated
      %td{class: cycle('odd', 'even')}= pretty_time(@post.tagged_at)
    %tr
      %td.sub.width-150 Status
      %td{class: cycle('odd', 'even')}
        - case @post.status
        - when Post::STATUS_ACTIVE
          = image_tag "/images/book_open.png", class: 'vmid', title: "In Progress"
          In Progress
        - when Post::STATUS_COMPLETE
          = image_tag "/images/book.png", class: 'vmid', title: "In Progress"
          Complete
        - when Post::STATUS_HIATUS
          = image_tag "/images/hourglass.png", class: 'vmid', title: "In Progress"
          On Hiatus
        - when Post::STATUS_ABANDONED
          = image_tag "/images/book_grey.png", class: 'vmid', title: "In Progress"
          Abandoned