config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      post :username
    end
    member do
      put :password
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index
  resources :characters do
    member do
      get :replace
      post :do_replace
    end
    collection { get :facecasts }
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end

  # Forums
  resources :boards do collection { post :mark } end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
    collection { get :search }
  end
  resources :tags

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: :show
      resources :board_sections do # TODO other types
        collection { post :reorder }
      end
      resources :characters, only: [:show, :update]
      resources :posts, only: :show
    end
  end

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount ResqueWeb::Engine => "/resque_web"
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  include Presentable

  belongs_to :user
  belongs_to :template
  has_many :replies
  has_and_belongs_to_many :galleries

  validates_presence_of :url, :user, :keyword
  validate :url_is_url
  validate :uploaded_url_not_in_use
  nilify_blanks

  after_destroy :clear_icon_ids
  before_destroy :delete_from_s3

  def uploaded?
    url.to_s.starts_with?('https://d1anwqy6ci9o1i.cloudfront.net/')
  end

  def s3_key
    return unless uploaded?
    url[url.index('net/')+4..-1]
  end

  private

  def url_is_url
    return true if url.to_s.starts_with?('http://') || url.to_s.starts_with?('https://')
    self.url = url_was unless new_record?
    errors.add(:url, "must be an actual fully qualified url (http://www.example.com)")
  end

  def delete_from_s3
    return unless uploaded?
    resp = S3_BUCKET.delete_objects(delete: {objects: [{key: s3_key}], quiet: true})
  end

  def uploaded_url_not_in_use
    return unless uploaded?
    check = Icon.where(url: url)
    check = check.where('id != ?', id) unless new_record?
    return unless check.exists?
    self.url = url_was
    errors.add(:url, 'has already been taken')
  end

  def clear_icon_ids
    Reply.where(icon_id: id).update_all(icon_id: nil)
    Post.where(icon_id: id).update_all(icon_id: nil)
  end

  class UploadError < Exception
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  has_many :character_tags, dependent: :destroy
  has_many :characters, through: :character_tags

  validates_presence_of :user, :name
  validates :name, uniqueness: { scope: :type }

  def editable_by?(user)
    user.try(:admin?)
  end

  def as_json(*args, **kwargs)
    {id: self.id, text: self.name}
  end

  def merge_with(other_tag)
    transaction do
      PostTag.where(tag_id: other_tag.id).where(post_id: post_tags.pluck('distinct post_id')).delete_all
      PostTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      other_tag.destroy
    end
  end
end

app/controllers/icons_controller.rb
# frozen_string_literal: true
class IconsController < ApplicationController
  before_filter :login_required, except: :show
  before_filter :find_icon, except: :delete_multiple
  before_filter :require_own_icon, only: [:edit, :update, :replace, :do_replace, :destroy, :avatar]

  def delete_multiple
    icon_ids = (params[:marked_ids] || []).map(&:to_i).reject(&:zero?)
    if icon_ids.empty? or (icons = Icon.where(id: icon_ids)).empty?
      flash[:error] = "No icons selected."
      redirect_to galleries_path and return
    end

    if params[:gallery_delete]
      gallery = Gallery.find_by_id(params[:gallery_id])
      unless gallery
        flash[:error] = "Gallery could not be found."
        redirect_to galleries_path and return
      end
      if gallery.user_id != current_user.id
        flash[:error] = "That is not your gallery."
        redirect_to galleries_path and return
      end

      icons.each do |icon|
        next unless icon.user_id == current_user.id
        gallery.icons.delete(icon)
      end
      flash[:success] = "Icons removed from gallery."
      redirect_to gallery_path(gallery) and return
    end

    icons.each do |icon|
      next unless icon.user_id == current_user.id
      icon.destroy
    end
    flash[:success] = "Icons deleted."
    redirect_to gallery_path(id: params[:gallery_id] || 0)
  end

  def show
    @page_title = @icon.keyword
    use_javascript('galleries/index') if params[:view] == 'galleries'
    if params[:view] == 'posts'
      where_calc = Post.where(icon_id: @icon.id).where(id: Reply.where(icon_id: @icon.id).pluck('distinct post_id'))
      @posts = posts_from_relation(Post.where(where_calc.where_values.reduce(:or)).order('tagged_at desc'))
    end
  end

  def edit
    @page_title = 'Edit Icon: ' + @icon.keyword
  end

  def update
    unless @icon.update_attributes(params[:icon])
      flash.now[:error] = {}
      flash.now[:error][:message] = "Your icon could not be saved due to the following problems:"
      flash.now[:error][:array] = @icon.errors.full_messages
      @page_title = 'Edit icon: ' + @icon.keyword_was
      render action: :edit and return
    end

    flash[:success] = "Icon updated."
    redirect_to icon_path(@icon)
  end

  def replace
    @page_title = "Replace Icon: " + @icon.keyword
    all_icons = if @icon.has_gallery?
      @icon.galleries.map(&:icons).flatten.uniq.compact - [@icon]
    else
      current_user.galleryless_icons - [@icon]
    end
    @alts = all_icons.sort_by{|i| i.keyword.downcase }
    use_javascript('icons')
    gon.gallery = Hash[all_icons.map { |i| [i.id, {url: i.url, keyword: i.keyword}] }]
    gon.gallery[''] = {url: '/images/no-icon.png', keyword: 'No Icon'}

    all_posts = Post.where(icon_id: @icon.id) + Post.where(id: Reply.where(icon_id: @icon.id).pluck('distinct post_id'))
    @posts = all_posts.uniq
  end

  def do_replace
    unless params[:icon_dropdown].blank? || new_icon = Icon.find_by_id(params[:icon_dropdown])
      flash[:error] = "Icon could not be found."
      redirect_to replace_icon_path(@icon)
    end

    if new_icon && new_icon.user_id != current_user.id
      flash[:error] = "That is not your icon."
      redirect_to galleries_path
    end

    Post.transaction do
      replies = Reply.where(icon_id: @icon.id)
      replies = replies.where(post_id: params[:post_ids]) if params[:post_ids].present?
      replies.update_all(icon_id: new_icon.try(:id))

      posts = Post.where(icon_id: @icon.id)
      posts = posts.where(id: params[:post_ids]) if params[:post_ids].present?
      posts.update_all(icon_id: new_icon.try(:id))
    end

    flash[:success] = "All uses of this icon have been replaced."
    redirect_to icon_path(@icon)
  end

  def destroy
    gallery = @icon.galleries.first if @icon.galleries.count == 1
    @icon.destroy
    flash[:success] = "Icon deleted successfully."
    redirect_to gallery_path(gallery) and return if gallery
    redirect_to galleries_path
  end

  def avatar
    if current_user.update_attributes(avatar: @icon)
      flash[:success] = "Avatar has been set!"
    else
      flash[:error] = "Something went wrong."
    end
    redirect_to icon_path(@icon)
  end

  private

  def find_icon
    unless @icon = Icon.find_by_id(params[:id])
      flash[:error] = "Icon could not be found."
      redirect_to galleries_path
    end
  end

  def require_own_icon
    if @icon.user_id != current_user.id
      flash[:error] = "That is not your icon."
      redirect_to galleries_path
    end
  end
end

app/views/icons/edit.haml
- content_for :breadcrumbs do
  - if @icon.user_id == current_user.try(:id)
    = link_to "Galleries", galleries_path
  - else
    = link_to "#{@icon.user.username}", user_path(@icon.user)
    &raquo;
    = link_to "#{@icon.user.username}'s Galleries", user_galleries_path(@icon.user)
  &raquo;
  = link_to @icon.keyword, icon_path(@icon)
  &raquo;
  %b Edit

= form_for @icon, :url => icon_path(@icon), :method => :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2}
        Edit Icon
    %tr
      %td.green.centered{colspan: 2}= icon_tag @icon
    %tr
      %th.sub URL
      %td.even
        - if @icon.uploaded?
          = image_tag "/images/accept.png", class: 'vmid'
          Uploaded to site
        - else
          = f.text_field :url, :placeholder => "URL", :class => 'text'
    %tr
      %th.sub Keyword
      %td.odd= f.text_field :keyword, :placeholder => "Keyword", :class => 'text'
    %tr
      %th.sub Credit
      %td.even= f.text_field :credit, :placeholder => "Credit", :class => 'text'
    %tr.submit-row
      %th.subber{colspan: 2}
        = submit_tag "Save", class: 'button'

app/views/icons/replace.haml
- content_for :breadcrumbs do
  = link_to "Galleries", galleries_path
  &raquo;
  = link_to @icon.keyword, icon_path(@icon)
  &raquo;
  %b= link_to 'Replace', replace_icon_path(@icon)

= form_for @icon, url: do_replace_icon_path(@icon), method: :post do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Replace All Uses of Icon
    %tr
      %th.sub Current
      %th.sub New
    %tr
      %td.green.width-150.centered.vtop
        = icon_tag @icon
        %br
        = @icon.keyword
      %td.green.width-150.centered
        - if @alts.first
          = icon_tag @alts.first, id: 'new_icon'
        - else
          = no_icon_tag id: 'new_icon'
        %br
        = select_tag :icon_dropdown, options_for_select(@alts.map{|i| [i.keyword, i.id]}, @alts.first.try(:id)), prompt: "No Icon"
    - if @posts.present?
      %tr
        %th.sub{colspan: 2} Optional: Select Post(s)
      %tr
        %td.odd.centered{colspan: 2}
          .details *If none are selected, replaces all uses*
    - @posts.each do |post|
      %tr
        %td{colspan: 2, class: cycle('even', 'odd')}
          = check_box_tag :'post_ids[]', post.id
          = link_to post.subject, post_path(post)
    %tr
      %th.subber{colspan: 2}= submit_tag "Replace", class: 'button'

app/views/icons/show.haml
- content_for :breadcrumbs do
  - if @icon.user_id == current_user.try(:id)
    = link_to "Galleries", galleries_path
  - else
    = link_to "#{@icon.user.username}", user_path(@icon.user)
    &raquo;
    = link_to "#{@icon.user.username}'s Galleries", user_galleries_path(@icon.user)
  &raquo;
  = link_to @icon.keyword, icon_path(@icon)
  &raquo;
  - if params[:view] == 'galleries'
    %b Galleries
  - elsif params[:view] == 'posts'
    %b Posts
  - else
    %b Stats

%table{style: 'width:150px;float: left;'}
  %tr
    %th.centered.icon-keyword= @icon.keyword
  %tr
    %td.green.centered.icon-icon= icon_tag @icon
  - if @icon.credit
    %tr
      %td.green.centered
        .details= @icon.credit
  %tr
    %td.centered{class: cycle('even', 'odd')}
      = link_to icon_path(@icon, view: 'stats') do
        = image_tag '/images/chart_bar.png'
        Stats
  %tr
    %td.centered{class: cycle('even', 'odd')}
      = link_to icon_path(@icon, view: 'galleries') do
        = image_tag '/images/photos.png'
        &nbsp;Galleries
  %tr
    %td.centered{class: cycle('even', 'odd')}
      = link_to icon_path(@icon, view: 'posts') do
        = image_tag '/images/book_open.png'
        Posts
  - if @icon.user_id == current_user.try(:id)
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to edit_icon_path(@icon) do
          = image_tag '/images/pencil.png'
          Edit Icon
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to avatar_icon_path(@icon), method: :post do
          = image_tag '/images/status_online.png'
          Set as Default
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to replace_icon_path(@icon) do
          = image_tag '/images/swap.png', style: 'width: 16px;'
          Replace Icon
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to icon_path(@icon), method: :delete, confirm: 'Are you sure you want to delete this icon?' do
          = image_tag '/images/cross.png'
          Delete Icon

- if params[:view] == 'galleries'
  .post-header
    .padding-15 Galleries
  %table.float-left{style: 'width: calc(100% - 150px);'}
    - if @icon.galleries.exists?
      - @icon.galleries.order(:name).each do |gallery|
        = render partial: 'galleries/single', locals: {gallery: gallery, klass: 'subber', skip_forms: true}
    - else
      %tr
        %td.even.centered — No galleries yet —
- elsif params[:view] == 'posts'
  - content_for :posts_title do
    Posts Containing Icon
  %table{style: 'width: calc(100% - 150px); float:left;'}
    = render partial: 'posts/list', locals: {posts: @posts, style: 'width: calc(100% - 150px); float:left;'}
- else
  - posts_using = Post.where(icon_id: @icon.id)
  - replies_using = Reply.where(icon_id: @icon.id)
  .post-header
    .padding-15 Stats
  %table{style: 'width: calc(100% - 150px); float:left;'}
    %tr
      %th.sub.width-150 Times Used
      %td.even= link_to (posts_using.count + replies_using.count).to_s, search_replies_path(commit: true, icon_id: @icon.id)
    %tr
      %th.sub.width-150 Posts In
      %td.even= (posts_using.pluck(:id) + replies_using.pluck('distinct post_id')).uniq.count